version: '3'

services:
  stateful-auth-api:
    container_name: stateful-auth-api
    build:
      context: "./stateful-auth-api"
      dockerfile: Dockerfile
    image: stateful-auth
    environment:
      DB_HOST: stateful-auth-db
      DB_PORT: 5432
      DB_NAME: auth-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: stateful-redis
      REDIS_PORT: 6379
    networks:
      - stateful-auth
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
    depends_on:
      - stateful-auth-db
      - stateful-redis

  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - stateful-auth
    ports:
      - "5433:5432"

  stateful-any-api:
    container_name: stateful-any-api
    build:
      context: "./stateful-any-api"
      dockerfile: Dockerfile
    image: stateful-any
    environment:
      STATEFUL_AUTH_BASE_URL: "http://stateful-auth-api:8082"
    networks:
      - stateful-auth
    ports:
      - "8083:8083"
    volumes:
      - ./:/app

  stateful-redis:
    container_name: stateful-redis
    image: redis:latest
    networks:
        - stateful-auth
    ports:
        - "6379:6379"

networks:
  stateful-auth:
    driver: bridge