version: '3'

services:
  stateful-auth:
    container_name: stateful-auth-api
    build:
      context: .
      dockerfile: Dockerfile
    image: stateful-auth
    environment:
      DB_HOST: stateful-auth-db
      DB_PORT: 5432
      DB_NAME: auth-db
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - stateful-auth
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
    depends_on:
      - stateful-auth-db

  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - stateful-auth
    ports:
      - "5433:5432"

networks:
  stateful-auth:
    driver: bridge